/*
    Copyright (C) 2019  RadWolfie

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <map>
#include <string>

#include "unittest.hpp"

static const std::map<std::string, version_ranges> database_min = {

    {"CMcpxAPU_ServiceDeferredCommandsLow",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CSensaura3d_GetFullHRTFFilterPair", {3911, 4039, VER_NONE, VER_NONE}},
    {"CSensaura3d_GetLiteHRTFFilterPair", {3911, 4039, VER_NONE, VER_NONE}},
    {"CFullHRTFSource_GetCenterVolume", {4039, 4242, 5344, VER_MAX}},
    {"CLightHRTFSource_GetCenterVolume", {4039, 4242, 5344, VER_MAX}},
    {"CHRTFSource_SetFullHRTF5Channel", {4039, 4242, 5344, VER_MAX}},
    {"CHRTFSource_SetLightHRTF5Channel", {4039, 4242, 5344, VER_MAX}},
    {"CHRTFSource_SetFullHRTF4Channel", {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CHRTFSource_SetLightHRTF4Channel", {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CFullHrtfSource_GetHrtfFilterPair", {4242, 5344, VER_NONE, VER_NONE}},
    {"CLightHrtfSource_GetHrtfFilterPair", {4242, 5344, VER_NONE, VER_NONE}},
    {"CHrtfSource_SetAlgorithm_FullHrtf", {4242, 5344, VER_NONE, VER_NONE}},
    {"CHrtfSource_SetAlgorithm_LightHrtf", {4242, 5344, VER_NONE, VER_NONE}},
    {"CDirectSound_DoWork", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundUseFullHRTF", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundUseLightHRTF", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundUseFullHRTF4Channel", {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundUseLightHRTF4Channel", {5344, VER_MAX, VER_NONE, VER_NONE}},

    {"DirectSoundCreate", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundCreateBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundCreateStream", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundDoWork", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundGetSampleTime", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundOverrideSpeakerConfig", {4039, VER_MAX, VER_NONE, VER_NONE}},
};

static const std::map<std::string, version_ranges> database_full = {
    {"XAudioCalculatePitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DirectSoundEnterCriticalSection", {3911, VER_MAX, VER_NONE, VER_NONE}},
    //========================================================
    {"DSound_CRefCount_AddRef", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"DSound_CRefCount_Release", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Commit3dSettings", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Set3dDistanceFactor", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Set3dDopplerFactor", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Set3dParameters", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Set3dPosition", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Set3dRolloffFactor", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_Set3dVelocity", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_SetI3DL2Listener", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxAPU_SetMixBinHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxAPU_SynchPlayback", {4831, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound3DCalculator_Calculate3D",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound3DCalculator_GetMixBinVolumes",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound3DCalculator_GetPanData",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound3DCalculator_GetVoiceData",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_GetVoiceProperties",
     {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dConeOrientation", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dConeOutsideVolume",
     {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dMaxDistance", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dMinDistance", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dMode", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dPosition", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dVelocity", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetEG", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetFilter", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetI3DL2Source", {3911, 4039, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetLFO", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetMixBins", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetPitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_SetVolume", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Commit3dSettings", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxVoiceClient_Set3dParameters", {3911, 4039, VER_NONE, VER_NONE}},
    {"CDirectSoundVoiceSettings_SetMixBinVolumes",
     {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_CommitDeferredSettings",
     {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_GetVoiceProperties",
     {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_Set3DVoiceData", {5455, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetAllParameters", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetConeAngles", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetConeOrientation",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetConeOutsideVolume",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetDistanceFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetDopplerFactor", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetEG", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetFilter", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetFormat", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetI3DL2Source", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetLFO", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetMaxDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetMinDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetMixBins", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetMixBinVolumes", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetMode", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetOutputBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetPitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetFrequency", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetRolloffCurve", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetRolloffFactor", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_SetVolume", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundVoice_Use3DVoiceData", {5558, VER_MAX, VER_NONE, VER_NONE}},

    //========================================================
    {"CDirectSoundBufferSettings_SetBufferData",
     {3911, VER_MAX, VER_NONE, VER_NONE}},

    {"CMcpxBuffer_GetCurrentPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_GetStatus", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_Pause", {4721, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_Pause_Ex", {4721, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_Play", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_Play_Ex", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_SetBufferData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_SetCurrentPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_Stop", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxBuffer_Stop_Ex", {4134, VER_MAX, VER_NONE, VER_NONE}},

    {"CMcpxStream_Stop", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxStream_Stop_Ex", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxStream_Flush", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxStream_Discontinuity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxStream_GetStatus", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxStream_Pause", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CMcpxStream_Pause_Ex", {4361, VER_MAX, VER_NONE, VER_NONE}},

    //========================================================
    {"CDirectSoundBuffer_GetCurrentPosition",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_GetStatus", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_GetVoiceProperties",
     {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_Lock", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_Pause", {4721, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_PauseEx", {4721, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_PlayEx", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_Play", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_Set3DVoiceData", {5455, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetAllParameters",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetBufferData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetConeAngles", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetConeOrientation",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetConeOutsideVolume",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetCurrentPosition",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetDistanceFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetDopplerFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetEG", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetFilter", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetFormat", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetFrequency", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetI3DL2Source", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetLFO", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetLoopRegion", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetMaxDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetMinDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetMixBins", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetMixBinVolumes",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetMode", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetNotificationPositions",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetOutputBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetPitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetPlayRegion", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetRolloffCurve", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetRolloffFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_SetVolume", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_StopEx", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_Stop", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundBuffer_Use3DVoiceData", {5558, VER_MAX, VER_NONE, VER_NONE}},

    {"CDirectSoundStream_Constructor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    // These symbols are manual registered with special scan using above symbol.
    {"CDirectSoundStream_AddRef", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Discontinuity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Flush", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_GetInfo", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_GetStatus", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Process", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Release", {3911, VER_MAX, VER_NONE, VER_NONE}},
    // -------------------------------

    {"CDirectSoundStream_FlushEx", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_GetVoiceProperties",
     {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Pause", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_PauseEx", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Set3DVoiceData", {5455, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetAllParameters",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetConeAngles", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetConeOrientation",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetConeOutsideVolume",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetDistanceFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetDopplerFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetEG", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetFilter", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetFormat", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetFrequency", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetI3DL2Source", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetLFO", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetMaxDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetMinDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetMixBins", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetMixBinVolumes_12",
     {3911, 4039, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetMixBinVolumes_8",
     {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetMode", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetOutputBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetPitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetRolloffCurve", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetRolloffFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_SetVolume", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSoundStream_Use3DVoiceData", {5558, VER_MAX, VER_NONE, VER_NONE}},

    {"CDirectSound_CommitDeferredSettings",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_CommitEffectData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_CreateSoundBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_CreateSoundStream", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_DownloadEffectsImage", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_EnableHeadphones", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_GetCaps", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_GetEffectData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_GetOutputLevels", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_GetSpeakerConfig", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_GetTime", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_MapBufferData", {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetAllParameters", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetDistanceFactor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetDopplerFactor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetEffectData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetI3DL2Listener", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetMixBinHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetOrientation", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetRolloffFactor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_SynchPlayback", {4831, VER_MAX, VER_NONE, VER_NONE}},
    {"CDirectSound_UnmapBufferData", {5344, VER_MAX, VER_NONE, VER_NONE}},

    //========================================================
    {"IDirectSound3DCalculator_Calculate3D",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound3DCalculator_GetMixBinVolumes",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound3DCalculator_GetPanData",
     {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound3DCalculator_GetVoiceData",
     {5344, VER_MAX, VER_NONE, VER_NONE}},

    {"IDirectSoundBuffer_AddRef", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_GetCurrentPosition",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_GetStatus", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_GetVoiceProperties",
     {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Lock", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Pause", {4721, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_PauseEx", {4721, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Play", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_PlayEx", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Release", {3911, VER_MAX, VER_NONE, VER_NONE}},
    //{"IDirectSoundBuffer_Restore", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Set3DVoiceData", {5455, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetAllParameters",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetBufferData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetConeAngles", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetConeOrientation",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetConeOutsideVolume",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetCurrentPosition",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetDistanceFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetDopplerFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetEG", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetFilter", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetFormat", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetFrequency", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetI3DL2Source", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetLFO", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetLoopRegion", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetMaxDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetMinDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetMixBins", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetMixBinVolumes_12",
     {3911, 4039, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetMixBinVolumes_8",
     {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetMode", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetNotificationPositions",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetOutputBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetPitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetPlayRegion", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetRolloffCurve", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetRolloffFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_SetVolume", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Stop", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_StopEx", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Unlock", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundBuffer_Use3DVoiceData", {5558, VER_MAX, VER_NONE, VER_NONE}},

    {"IDirectSoundStream_GetVoiceProperties",
     {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_FlushEx", {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_Pause", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_PauseEx", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_Set3DVoiceData", {5455, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetAllParameters",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetConeAngles", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetConeOrientation",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetConeOutsideVolume",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetDistanceFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetDopplerFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetEG", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetLFO", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetFilter", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetFormat", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetFrequency", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetI3DL2Source", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetMaxDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetMinDistance", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetMixBins", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetMixBinVolumes_12",
     {3911, 4039, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetMixBinVolumes_8",
     {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetMode", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetOutputBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetPitch", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetRolloffCurve", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetRolloffFactor",
     {4134, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_SetVolume", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSoundStream_Use3DVoiceData", {5558, VER_MAX, VER_NONE, VER_NONE}},

    {"IDirectSound_AddRef", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_CommitDeferredSettings",
     {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_CommitEffectData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    //{"IDirectSound_Compact", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_CreateSoundBuffer", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_CreateSoundStream", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_DownloadEffectsImage", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_EnableHeadphones", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_GetCaps", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_GetEffectData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_GetOutputLevels", {4361, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_GetSpeakerConfig", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_GetTime", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_MapBufferData", {5344, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_Release", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetAllParameters", {3911, VER_MAX, VER_NONE, VER_NONE}},
    //{"IDirectSound_SetCooperativeLevel", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetDistanceFactor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetDopplerFactor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetEffectData", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetI3DL2Listener", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetMixBinHeadroom", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetOrientation", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetPosition", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetRolloffFactor", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SetVelocity", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_SynchPlayback", {4831, VER_MAX, VER_NONE, VER_NONE}},
    {"IDirectSound_UnmapBufferData", {5344, VER_MAX, VER_NONE, VER_NONE}},

    // HRTF functions are moved to db_min variable.

    // DirectSound functions are moved to db_min variable.

    {"IsValidFormat", {3911, 4361, VER_NONE, VER_NONE}},

    {"XAudioDownloadEffectsImage", {4039, VER_MAX, VER_NONE, VER_NONE}},
    {"XAudioSetEffectData", {5028, VER_MAX, VER_NONE, VER_NONE}},
    {"XAudioCreatePcmFormat", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"XAudioCreateAdpcmFormat", {3911, VER_MAX, VER_NONE, VER_NONE}},

    {"XFileCreateMediaObject", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"XFileCreateMediaObjectAsync", {4432, VER_MAX, VER_NONE, VER_NONE}},
    {"XFileCreateMediaObjectEx", {4242, VER_MAX, VER_NONE, VER_NONE}},

    {"XWaveFileCreateMediaObject", {3911, VER_MAX, VER_NONE, VER_NONE}},
    {"XWaveFileCreateMediaObjectEx", {4242, VER_MAX, VER_NONE, VER_NONE}},
};

void getLibraryDSOUND(const library_list **db_min, const library_list **db_full)
{
	*db_min = &database_min;
	*db_full = &database_full;
}
